// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Model;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApkaContext))]
    partial class ApkaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Entities.DostawcaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Miejscowosc");

                    b.Property<string>("NazwaDostawcy");

                    b.Property<string>("RodzajDostawcy");

                    b.HasKey("id");

                    b.ToTable("Dostawcy");
                });

            modelBuilder.Entity("WebApplication1.Entities.SklepEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Miejscowosc");

                    b.Property<string>("NazwaSklepu");

                    b.Property<string>("RodzajSklepu");

                    b.HasKey("id");

                    b.ToTable("Sklepy");
                });

            modelBuilder.Entity("WebApplication1.Entities.TowarEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Miejscowosc");

                    b.Property<string>("NazwaTowaru");

                    b.Property<string>("RozmiarTowaru");

                    b.Property<string>("TypTowaru");

                    b.HasKey("id");

                    b.ToTable("Towary");
                });
#pragma warning restore 612, 618
        }
    }
}
